"use client";
import { useState, useRef, useEffect, FormEvent } from "react";
import { Send, StopCircle, Paperclip, X, Brain, ChevronDown } from "lucide-react";
import { Toaster, toast } from "sonner";
import { getAnonUserId } from "@/lib/auth-anon";
function fileToDataURL(f:File):Promise<string>{return new Promise((rs,rj)=>{const r=new FileReader();r.onload=()=>rs(r.result as string);r.onerror=()=>rj(new Error("File read error"));r.readAsDataURL(f)})}
type Provider="openrouter"|"agentrouter";
const PROVIDERS:{id:Provider;name:string;color:string}[]=[{id:"openrouter",name:"OpenRouter",color:"border-blue-500/30 text-blue-400 bg-blue-500/10"},{id:"agentrouter",name:"AgentRouter",color:"border-purple-500/30 text-purple-400 bg-purple-500/10"}];
interface MI{id:string;name:string;f:boolean;provider:Provider;p:string;d:string}
const MODELS:MI[]=[{id:"nvidia/nemotron-3-super-120b-a12b:free",name:"Nemotron 3 Super",f:true,provider:"openrouter",p:"NVIDIA",d:"120B gratuit"},{id:"nvidia/nemotron-3-ultra-550b-a55b:free",name:"Nemotron 3 Ultra",f:true,provider:"openrouter",p:"NVIDIA",d:"550B gratuit"},{id:"nvidia/nemotron-nano-9b-v2:free",name:"Nemotron Nano 9B",f:true,provider:"openrouter",p:"NVIDIA",d:"9B gratuit"},{id:"poolside/laguna-s-2.1:free",name:"Laguna S 2.1",f:true,provider:"openrouter",p:"Poolside",d:"Coding gratuit"},{id:"cohere/north-mini-code:free",name:"North Mini Code",f:true,provider:"openrouter",p:"Cohere",d:"Code gratuit"},{id:"inclusionai/ling-3.0-flash:free",name:"Ling 3.0 Flash",f:true,provider:"openrouter",p:"InclusionAI",d:"Rapide gratuit"},{id:"google/gemma-4-31b-it:free",name:"Gemma 4 31B",f:true,provider:"openrouter",p:"Google",d:"Vision gratuit"},{id:"google/gemma-4-26b-a4b-it:free",name:"Gemma 4 26B",f:true,provider:"openrouter",p:"Google",d:"Vision gratuit"},{id:"nvidia/nemotron-nano-12b-v2-vl:free",name:"Nemotron Nano VL",f:true,provider:"openrouter",p:"NVIDIA",d:"Vision gratuit"},{id:"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",name:"Nemotron Omni",f:true,provider:"openrouter",p:"NVIDIA",d:"Omni gratuit"},{id:"openai/gpt-oss-20b:free",name:"GPT-OSS 20B",f:true,provider:"openrouter",p:"OpenAI",d:"Open source"},{id:"deepseek/deepseek-chat-v3-0324",name:"DeepSeek V3",f:false,provider:"openrouter",p:"DeepSeek",d:"$0.27/$1.1"},{id:"openai/gpt-4o-mini",name:"GPT-4o Mini",f:false,provider:"openrouter",p:"OpenAI",d:"$0.15/$0.6"},{id:"anthropic/claude-3.5-sonnet",name:"Claude 3.5 Sonnet",f:false,provider:"openrouter",p:"Anthropic",d:"$3/$15"},{id:"meta-llama/llama-4-maverick",name:"Llama 4 Maverick",f:false,provider:"openrouter",p:"Meta",d:"$0.2/$0.9"},{id:"google/gemini-2.5-pro-preview-06-05",name:"Gemini 2.5 Pro",f:false,provider:"openrouter",p:"Google",d:"$1.25/$10"},{id:"mistralai/mistral-large-2411",name:"Mistral Large",f:false,provider:"openrouter",p:"Mistral",d:"$2/$6"},{id:"claude-sonnet-4-5-20250929",name:"Claude Sonnet 4.5",f:false,provider:"agentrouter",p:"Anthropic",d:"via AgentRouter"},{id:"claude-haiku-3-5-20241022",name:"Claude Haiku 3.5",f:false,provider:"agentrouter",p:"Anthropic",d:"via AgentRouter"},{id:"gpt-4o",name:"GPT-4o",f:false,provider:"agentrouter",p:"OpenAI",d:"via AgentRouter"},{id:"gpt-4o-mini",name:"GPT-4o Mini (AR)",f:false,provider:"agentrouter",p:"OpenAI",d:"via AgentRouter"},{id:"deepseek-r1",name:"DeepSeek R1 (AR)",f:false,provider:"agentrouter",p:"DeepSeek",d:"via AgentRouter"},{id:"gemini-2.0-flash-001",name:"Gemini 2.0 Flash",f:false,provider:"agentrouter",p:"Google",d:"via AgentRouter"},{id:"glm-4.5-air",name:"GLM-4.5 Air",f:false,provider:"agentrouter",p:"Z.ai",d:"via AgentRouter"}];
export function ChatInterface({convId:ic}:{convId?:string}){const[cid,scid]=useState(ic||"");const[msgs,smsgs]=useState<any[]>([]);const[inp,sinp]=useState("");const[ld,sld]=useState(false);const[md,smd]=useState("nvidia/nemotron-3-super-120b-a12b:free");const[pv,spv]=useState<Provider>("openrouter");const[sm,ssm]=useState(false);const[sp,ssp]=useState(false);const[ims,sims]=useState<{file:File;preview:string}[]>([]);const[srch,ssrch]=useState("");const[ft,sft]=useState<"all"|"free"|"paid">("all");const[hk,shk]=useState(false);const[pk,spk]=useState<Record<Provider,boolean>>({openrouter:false,agentrouter:false});const sref=useRef<HTMLDivElement>(null);const firef=useRef<HTMLInputElement>(null);const aref=useRef<AbortController|null>(null);const pref=useRef<HTMLDivElement>(null);const ppref=useRef<HTMLDivElement>(null);const anonId=typeof window!=="undefined"?getAnonUserId():"";
useEffect(()=>{if(!cid||!anonId){smsgs([]);return}fetch(`/api/messages?conversationId=${cid}`,{headers:{"x-anon-user-id":anonId}}).then(r=>r.json()).then(d=>{if(d.messages)smsgs(d.messages.map((m:any)=>({id:m.id,role:m.role,content:m.content,model:m.model})))})},[cid,anonId]);
useEffect(()=>{if(!anonId)return;fetch("/api/keys",{headers:{"x-anon-user-id":anonId}}).then(r=>r.json()).then(d=>{const ks=d.keys||[];shk(ks.length>0);const pk2:Record<Provider,boolean>={openrouter:false,agentrouter:false};ks.forEach((k:any)=>{if(k.provider==="openrouter"||k.provider==="agentrouter")pk2[k.provider]=true});if(!pk2.agentrouter)pk2.agentrouter=true;spk(pk2)})},[anonId]);
useEffect(()=>{if(sref.current)sref.current.scrollTop=sref.current.scrollHeight},[msgs]);
useEffect(()=>{const h=(e:MouseEvent)=>{if(pref.current&&!pref.current.contains(e.target as Node))ssm(false);if(ppref.current&&!ppref.current.contains(e.target as Node))ssp(false)};document.addEventListener("mousedown",h);return()=>document.removeEventListener("mousedown",h)},[]);
function swp(p:Provider){spv(p);ssp(false);const fm=MODELS.find(m=>m.provider===p);if(fm)smd(fm.id)}
const cp=PROVIDERS.find(p=>p.id===pv)!;const pms=MODELS.filter(m=>m.provider===pv);const fms=pms.filter(m=>m.f);const pms2=pms.filter(m=>!m.f);const fms3=pms.filter(m=>{if(ft==="free"&&!m.f)return false;if(ft==="paid"&&m.f)return false;if(srch&&!m.name.toLowerCase().includes(srch.toLowerCase())&&!m.p.toLowerCase().includes(srch.toLowerCase()))return false;return true});
function sel(id:string){smd(id);ssm(false);ssrch("")}
function rmi(i:number){sims(prev=>prev.filter((_,idx)=>idx!==i))}
function hf(fl:FileList){const ni:{file:File;preview:string}[]=[];for(let i=0;i<fl.length;i++){const f=fl[i];if(!f.type.startsWith("image/")){toast.error("Images uniquement");continue}if(f.size>10485760){toast.error(">10 MB");continue}if(ims.length+ni.length>=5){toast.error("Max 5");break}ni.push({file:f,preview:URL.createObjectURL(f)})}sims(prev=>[...prev,...ni])}
function hp(e:React.ClipboardEvent){const fs:File[]=[];for(let i=0;i<e.clipboardData.items.length;i++){if(e.clipboardData.items[i].type.startsWith("image/")){const f=e.clipboardData.items[i].getAsFile();if(f)fs.push(f)}}if(fs.length){const dt=new DataTransfer();fs.forEach(f=>dt.items.add(f));hf(dt.files)}}
async function hs(e:FormEvent){e.preventDefault();if((!inp.trim()&&ims.length===0)||ld)return;if(!hk){toast.error("Ajoutez une cle API");return}if(!pk[pv]){toast.error(`Aucune cle ${PROVIDERS.find(p=>p.id===pv)?.name}`);return}
let cid2=cid;if(!cid2){try{const res=await fetch("/api/conversations",{method:"POST",headers:{"Content-Type":"application/json","x-anon-user-id":anonId},body:JSON.stringify({title:inp.trim().slice(0,60)||"Nouveau chat",model:md,provider:pv})});const d=await res.json();if(d.conversation){cid2=d.conversation.id;scid(cid2);window.dispatchEvent(new CustomEvent("elshalflow_refresh_convs"));window.history.pushState({},"",`/chat?c=${cid2}`)}}catch{}}
let uc:any;if(ims.length>0){const pts:any[]=[];if(inp.trim())pts.push({type:"text",text:inp.trim()});const dus=await Promise.all(ims.map(img=>fileToDataURL(img.file)));for(const url of dus)pts.push({type:"image_url",image_url:{url}});uc=pts}else{uc=inp.trim()}
smsgs(prev=>[...prev,{id:"u"+Date.now(),role:"user",content:inp.trim()||"[Image]",images:ims.map(i=>i.preview),model:md,provider:pv}]);sinp("");sims([]);sld(true);
const ams=msgs.map((m:any)=>{if(m.images?.length){const pts:any[]=[];if(typeof m.content==="string"&&m.content!=="[Image]")pts.push({type:"text",text:m.content});for(const url of m.images)pts.push({type:"image_url",image_url:{url}});return{role:m.role,content:pts}}return{role:m.role,content:m.content}});ams.push({role:"user",content:uc});
const aid="a"+Date.now();smsgs(prev=>[...prev,{id:aid,role:"assistant",content:"",model:md,provider:pv}]);aref.current=new AbortController();
try{const isAR=pv==="agentrouter";const arKey="Sk-CXBlcOzzMoBkLd6zkgqwUKeTZ5wl8HCb9tbu6vOBtIxLIXYn";const resp=isAR?await fetch("https://agentrouter.org/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+arKey},body:JSON.stringify({model:md,messages:ams,max_tokens:2048,stream:true}),signal:aref.current.signal}):await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json","x-anon-user-id":anonId},body:JSON.stringify({messages:ams,model:md,provider:pv,conversationId:cid2}),signal:aref.current.signal});
if(!resp.ok){const err=await resp.json().catch(()=>({}));throw new Error(err.response||err.error||`HTTP ${resp.status}`)}
const rd=resp.body?.getReader();if(!rd)throw new Error("Stream non disponible");const dec=new TextDecoder();let buf="";let sc2="";let sm2=md;let lu=0;
function fu(){const n=Date.now();if(n-lu>=30){smsgs(prev=>prev.map(m=>m.id===aid?{...m,content:sc2,model:sm2}:m));lu=n}}
while(true){const{done,value}=await rd.read();if(done)break;buf+=dec.decode(value,{stream:true});let bd:number;while((bd=buf.indexOf("\n\n"))!==-1){const fr=buf.slice(0,bd);buf=buf.slice(bd+2);const di=fr.lastIndexOf("data: ");if(di===-1)continue;try{const p=JSON.parse(fr.slice(di+6));if(p.delta){sc2+=p.delta;if(p.model)sm2=p.model;fu()}if(p.done&&p.full)sc2=p.full;if(p.error)toast.error(p.error)}catch{}}fu()}
smsgs(prev=>prev.map(m=>m.id===aid?{...m,content:sc2||"(vide)",model:sm2}:m));window.dispatchEvent(new CustomEvent("elshalflow_refresh_convs"))}catch(err:any){if(err.name!=="AbortError"){toast.error(err.message);smsgs(prev=>prev.map(m=>m.id===aid?{...m,content:`Erreur: ${err.message}`}:m))}}finally{sld(false);aref.current=null}}
function rm2(text:string){let h=text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");h=h.replace(/```(\w*)\n?([\s\S]*?)```/g,'<pre class="bg-secondary/50 rounded-lg p-2.5 my-1.5 overflow-x-auto text-[11px]"><code>$2</code></pre>');h=h.replace(/`([^`]+)`/g,'<code class="bg-secondary/50 px-1 py-0.5 rounded text-[11px]">$1</code>');h=h.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>");h=h.replace(/\n/g,"<br/>");return<div dangerouslySetInnerHTML={{__html:h}}/>}
const cm=MODELS.find(m=>m.id===md)||MODELS[0];
return(<div className="flex flex-col h-full bg-background"><Toaster richColors theme="dark" position="top-center"/><div ref={sref} className="flex-1 overflow-y-auto pb-4">{msgs.length===0?(<div className="flex flex-col items-center justify-center h-full px-6 text-center py-12"><div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center mb-6"><Brain className="w-8 h-8 text-primary/40"/></div><h1 className="text-2xl font-bold mb-2">ElshalflowAI</h1><p className="text-muted-foreground text-sm max-w-xs mb-6">Assistant IA avec OpenRouter + AgentRouter</p>{!hk?(<div className="p-4 rounded-xl border border-amber-500/30 bg-amber-500/5 max-w-xs"><p className="text-amber-400 text-sm font-medium mb-1">Ajoutez votre cle API</p><p className="text-muted-foreground text-xs">Menu lateral → Cles API</p></div>):(<div className="space-y-1"><p className="text-green-400 text-xs">Cle detectee — Pret !</p><p className="text-[10px] text-muted-foreground">{pk.openrouter&&"🔵 OpenRouter "}{pk.agentrouter&&"🟣 AgentRouter"}</p></div>)}</div>):(<div className="max-w-3xl mx-auto px-4 py-6 space-y-6">{msgs.map((m)=>(<div key={m.id} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[85%] break-words ${m.role==="user"?"flex flex-col items-end":""}`}>{m.role==="assistant"&&(<div className="flex items-center gap-1.5 mb-1 ml-1">{m.provider&&(<span className={`text-[9px] px-1 py-0 rounded ${PROVIDERS.find(p=>p.id===m.provider)?.color||""}`}>{PROVIDERS.find(p=>p.id===m.provider)?.name}</span>)}<span className="text-[10px] text-muted-foreground font-medium">{MODELS.find(x=>x.id===m.model)?.name||m.model}</span></div>)}{m.images?.length>0&&(<div className="flex gap-1 mb-1 flex-wrap justify-end">{m.images.map((url:string,i:number)=><img key={i} src={url} alt="" className="max-w-[120px] max-h-[120px] rounded-lg object-cover"/>)}</div>)}<div className={`px-4 py-3 text-[14px] leading-relaxed rounded-2xl ${m.role==="user"?"bg-primary/15 text-foreground rounded-br-md":"text-foreground"}`}>{m.content?rm2(m.content):<span className="flex gap-1.5 py-1"><span className="w-2 h-2 rounded-full bg-muted-foreground animate-bounce"/><span className="w-2 h-2 rounded-full bg-muted-foreground animate-bounce" style={{animationDelay:"0.15s"}}/><span className="w-2 h-2 rounded-full bg-muted-foreground animate-bounce" style={{animationDelay:"0.3s"}}/></span>}</div></div></div>))}</div>)}</div>
{ims.length>0&&(<div className="px-4 pb-1 flex gap-1.5 flex-wrap max-w-3xl mx-auto w-full">{ims.map((img,i)=>(<div key={i} className="relative group"><img src={img.preview} alt="" className="h-14 w-14 rounded-lg object-cover border border-border"/><button type="button" onClick={()=>rmi(i)} className="absolute -top-1.5 -right-1.5 bg-red-500 rounded-full p-0.5 opacity-0 group-hover:opacity-100 transition-opacity"><X className="h-2.5 w-2.5 text-white"/></button></div>))}</div>)}
<div className="border-t border-border px-3 py-3"><div className="max-w-3xl mx-auto relative" ref={pref}>
<div className="flex items-center gap-2 mb-2" ref={ppref}><button type="button" onClick={()=>ssp(!sp)} className={`text-[11px] px-2.5 py-1 rounded-full border flex items-center gap-1 shrink-0 ${cp.color}`}><span className="font-medium">{cp.name}</span><ChevronDown className="w-3 h-3"/></button>{pk[pv]?(<span className="text-[10px] text-green-400">✓ Cle OK</span>):(<span className="text-[10px] text-amber-400">⚠ Pas de cle</span>)}{sp&&(<div className="absolute top-full mt-1 left-0 bg-card border border-border rounded-lg shadow-xl z-50 py-1 min-w-[160px]">{PROVIDERS.map(p=>(<button key={p.id} type="button" onClick={()=>swp(p.id)} className={`w-full text-left px-3 py-2 text-xs hover:bg-secondary/50 flex items-center justify-between ${p.id===pv?"bg-primary/5":""}`}><span className={`font-medium ${p.id===pv?"text-foreground":"text-muted-foreground"}`}>{p.name}</span>{pk[p.id]?<span className="text-[10px] text-green-400">✓</span>:<span className="text-[10px] text-muted-foreground">—</span>}</button>))}</div>)}</div>
<form onSubmit={hs} className="flex items-end gap-2 bg-secondary/40 rounded-2xl border border-border focus-within:border-primary/30 transition-colors px-3 py-2"><button type="button" onClick={()=>firef.current?.click()} className="p-1 text-muted-foreground hover:text-foreground shrink-0"><Paperclip className="h-4 w-4"/></button><input ref={firef} type="file" accept="image/*" multiple className="hidden" onChange={e=>e.target.files&&hf(e.target.files)}/><textarea value={inp} onChange={e=>sinp(e.target.value)} onPaste={hp} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();hs(e as any)}}} placeholder="Message ElshalflowAI..." rows={1} className="flex-1 bg-transparent resize-none text-[14px] outline-none placeholder:text-muted-foreground min-h-[24px] max-h-[120px] py-0.5" disabled={ld}/><div className="flex items-center gap-1 shrink-0">{ld?(<button type="button" onClick={()=>aref.current?.abort()} className="p-1 text-red-400" title="Arreter"><StopCircle className="h-4 w-4"/></button>):(<button type="submit" disabled={!inp.trim()&&ims.length===0} className="p-1.5 bg-primary rounded-full text-primary-foreground hover:bg-primary/80 disabled:opacity-30 transition-all"><Send className="h-3.5 w-3.5"/></button>)}</div></form>
<div className="mt-2 flex items-center gap-2 overflow-x-auto pb-1"><button type="button" onClick={()=>{ssm(!sm);ssrch("");sft("all")}} className={`text-[12px] px-3 py-1.5 rounded-full border transition-colors flex items-center gap-1.5 shrink-0 ${cm.f?"border-green-500/30 text-green-400 bg-green-500/10":"border-border text-muted-foreground"}`}><span className="font-medium">{cm.name}</span>{cm.f&&<span className="text-[10px] opacity-60">Gratuit</span>}<svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m6 9 6 6 6-6"/></svg></button>{pms.filter(m=>m.f).slice(0,6).map(m=>(<button key={m.id} type="button" onClick={()=>sel(m.id)} className={`text-[11px] px-2.5 py-1.5 rounded-full border whitespace-nowrap shrink-0 ${m.id===md?"border-primary/30 bg-primary/10 text-primary":"border-border text-muted-foreground hover:border-primary/20"}`}>{m.name}</button>))}{pms2.length>0&&(<button type="button" onClick={()=>{ssm(true);sft("paid")}} className="text-[11px] px-2.5 py-1.5 rounded-full border border-border text-muted-foreground whitespace-nowrap shrink-0">+{pms2.length} payants</button>)}</div>
{sm&&(<div className="absolute bottom-full mb-2 left-0 right-0 bg-card border border-border rounded-xl shadow-2xl overflow-hidden z-50" style={{maxHeight:"60vh"}}><div className="p-3 border-b border-border space-y-2"><input value={srch} onChange={e=>ssrch(e.target.value)} placeholder="Search..." className="w-full bg-secondary/50 rounded-lg px-3 py-2 text-xs outline-none" autoFocus/><div className="flex gap-1">{(["all","free","paid"]as const).map(tab=>{const cnt=tab==="all"?pms.length:tab==="free"?fms.length:pms2.length;return(<button key={tab} type="button" onClick={()=>sft(tab)} className={`text-[11px] px-2.5 py-1 rounded-md ${ft===tab?tab==="free"?"bg-green-500/20 text-green-400":tab==="paid"?"bg-amber-500/20 text-amber-400":"bg-primary/20 text-primary":"text-muted-foreground"}`}>{tab==="all"?"Tous":tab==="free"?"Gratuits":"Payants"} ({cnt})</button>)})}</div></div><div className="overflow-y-auto" style={{maxHeight:"50vh"}}>{fms3.slice(0,30).map(m=>(<button key={m.id} type="button" onClick={()=>sel(m.id)} className={`w-full text-left px-3 py-2.5 hover:bg-secondary/50 flex items-center justify-between gap-2 border-b border-border/20 ${m.id===md?"bg-primary/5 border-l-2 border-l-primary":""}`}><div className="min-w-0"><div className="text-xs font-medium flex items-center gap-1.5">{m.name}{m.f?<span className="text-[10px] bg-green-500/15 text-green-400 px-1 py-0 rounded">Gratuit</span>:<span className="text-[10px] bg-amber-500/15 text-amber-400 px-1 py-0 rounded">Payant</span>}</div><div className="text-[10px] text-muted-foreground truncate">{m.provider==="agentrouter"?"🟣 AR":"🔵 OR"} · {m.p} · {m.d}</div></div>{m.id===md&&<div className="w-2 h-2 rounded-full bg-primary shrink-0"/>}</button>))}</div></div>)}
<p className="text-[10px] text-muted-foreground text-center mt-1.5">{hk?"Cle OK · ":"Ajoutez cle dans Cles API · "}{pv==="openrouter"?`${fms.length} gratuits`: ""} · {pms2.length} modeles · {cp.name}</p>
</div></div></div>)}
