"use client";
import { useState, useRef, useEffect, FormEvent } from "react";
import { useParams } from "next/navigation";
import { Send, StopCircle, Paperclip, X, Image, Brain, ChevronDown, Search } from "lucide-react";
import { Toaster, toast } from "sonner";
function toB64(f:File){return new Promise((rs:any,rj:any)=>{const r=new FileReader();r.onload=()=>rs(r.result);r.onerror=rj;r.readAsDataURL(f)})}
function getKey(){try{const v=localStorage.getItem("elshalflow_byok");return v?(JSON.parse(v).find((k:any)=>k.is_default)?.api_key||JSON.parse(v)[0]?.api_key||""):""}catch{return""}}
const M=[{id:"google/gemini-2.0-flash-001",name:"Gemini 2.0 Flash",f:true,p:"Google",r:"0",v:true},{id:"deepseek/deepseek-chat-v3-0324:free",name:"DeepSeek V3",f:true,p:"DeepSeek",r:"0",v:false},{id:"meta-llama/llama-4-maverick:free",name:"Llama 4 Maverick",f:true,p:"Meta",r:"0",v:false},{id:"mistralai/mistral-small-3.1-24b-instruct:free",name:"Mistral Small",f:true,p:"Mistral",r:"0",v:false},{id:"google/gemini-2.5-flash-preview-06-09",name:"Gemini 2.5 Flash",f:true,p:"Google",r:"0",v:true},{id:"openai/gpt-4o-mini",name:"GPT-4o Mini",f:false,p:"OpenAI",r:"0.15",v:true},{id:"openai/gpt-4o",name:"GPT-4o",f:false,p:"OpenAI",r:"2.5",v:true},{id:"anthropic/claude-3.5-sonnet",name:"Claude 3.5 Sonnet",f:false,p:"Anthropic",r:"3",v:true},{id:"google/gemini-2.5-pro-preview-06-05",name:"Gemini 2.5 Pro",f:false,p:"Google",r:"1.25",v:true},{id:"deepseek/deepseek-chat-v3-0324",name:"DeepSeek V3 Pro",f:false,p:"DeepSeek",r:"0.27",v:false},{id:"qwen/qwen3-235b-a22b",name:"Qwen 3 235B",f:false,p:"Alibaba",r:"0.35",v:false},{id:"mistralai/mistral-large-2411",name:"Mistral Large",f:false,p:"Mistral",r:"2",v:false}];

export function ChatInterface(){
const cid=(useParams()?.conversationId as string)||"d";
const[msgs,setMsgs]=useState<any[]>(()=>{try{return JSON.parse(localStorage.getItem("chat_"+cid)||"[]")}catch{return[]}});
const[input,setInput]=useState("");const[loading,setLoading]=useState(false);
const[model,setModel]=useState("google/gemini-2.0-flash-001");
const[models]=useState<any[]>(M);
const[showM,setShowM]=useState(false);const[images,setImages]=useState<any[]>([]);
const[ms,setMs]=useState("");const[mt,setMt]=useState("all");
const sr=useRef<HTMLDivElement>(null);const fr=useRef<HTMLInputElement>(null);
const ar=useRef<AbortController>(null);const dr=useRef<HTMLDivElement>(null);

useEffect(()=>{if(sr.current)sr.current.scrollTop=sr.current.scrollHeight},[msgs]);
useEffect(()=>{try{localStorage.setItem("chat_"+cid,JSON.stringify(msgs))}catch{}},[msgs,cid]);
useEffect(()=>{const h=(e:any)=>{if(dr.current&&!dr.current.contains(e.target))setShowM(false)};document.addEventListener("mousedown",h);return()=>document.removeEventListener("mousedown",h)},[]);

function sel(id:string){setModel(id);setShowM(false);setMs("")}
function rmImg(i:number){setImages((p:any)=>p.filter((_:any,x:number)=>x!==i))}
function hFiles(files:FileList){const n:any[]=[];for(let i=0;i<files.length;i++){if(!files[i].type.startsWith("image/")){toast.error("Image only");continue}if(files[i].size>10485760){toast.error(">10MB");continue}if(images.length+n.length>=5){toast.error("Max 5");break}n.push({file:files[i],preview:URL.createObjectURL(files[i])})}setImages((p:any)=>[...p,...n])}
function hPaste(e:any){const fs:File[]=[];for(let i=0;i<e.clipboardData.items.length;i++){if(e.clipboardData.items[i].type.startsWith("image/")){const f=e.clipboardData.items[i].getAsFile();if(f)fs.push(f)}}if(fs.length){const dt=new DataTransfer();fs.forEach(f=>dt.items.add(f));hFiles(dt.files)}}

async function handleSubmit(e:FormEvent){e.preventDefault();if((!input.trim()&&images.length===0)||loading)return;const b64s=await Promise.all(images.map((i:any)=>toB64(i.file)));const prvs=images.map((i:any)=>i.preview);let c:any=input||"[Image]";if(b64s.length){const p:any[]=[];if(input.trim())p.push({type:"text",text:input});b64s.forEach((b:string)=>p.push({type:"image_url",image_url:{url:b}}));c=p}const um:any={id:"u"+Date.now(),role:"user",content:input.trim()||"[Image]",images:prvs,model};setMsgs((p:any)=>[...p,um]);setInput("");setImages([]);setLoading(true);const ams=msgs.map((m:any)=>({role:m.role,content:m.images?.length?m.content||"[Image]":m.content}));ams.push({role:"user",content:c});const key=getKey();ar.current=new AbortController();const aid="a"+Date.now();setMsgs((p:any)=>[...p,{id:aid,role:"assistant",content:"",model}]);try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:ams,model,apiKey:key}),signal:ar.current!.signal});if(!res.ok){const e=await res.json();throw new Error(e.response||e.error||"Err "+res.status)}const rd=res.body?.getReader();if(!rd)throw new Error("No stream");const dec=new TextDecoder();let full="";while(true){const{done,value}=await rd.read();if(done)break;for(const line of dec.decode(value,{stream:true}).split("\n")){if(line.startsWith("data: ")){const d=line.slice(6);if(d==="[DONE]")continue;try{full+=JSON.parse(d).choices?.[0]?.delta?.content||""}catch{}}}setMsgs((p:any)=>p.map((m:any)=>m.id===aid?{...m,content:full}:m))}}catch(err:any){if(err.name!=="AbortError"){toast.error(err.message);setMsgs((p:any)=>p.map((m:any)=>m.id===aid?{...m,content:"Err: "+err.message}:m))}}finally{setLoading(false);ar.current=null}}

function render(text:string){let h=text.replace(/&/g,"&").replace(/</g,"<").replace(/>/g,">");h=h.replace(/```(\w*)\n?([\s\S]*?)```/g,'<pre class="bg-secondary/50 rounded-lg p-2.5 my-1.5 overflow-x-auto text-[11px]"><code>$2</code></pre>');h=h.replace(/`([^`]+)`/g,'<code class="bg-secondary/50 px-1 py-0.5 rounded text-[11px]">$1</code>');h=h.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>");h=h.replace(/\*(.+?)\*/g,"<em>$1</em>");h=h.replace(/\n/g,"<br/>");return <div dangerouslySetInnerHTML={{__html:h}}/>}

const cm=models.find((m:any)=>m.id===model)||M[0];const frees=models.filter((m:any)=>m.f);const paids=models.filter((m:any)=>!m.f);
const fm=models.filter((m:any)=>{if(mt==="free"&&!m.f)return false;if(mt==="paid"&&m.f)return false;if(ms&&!m.name.toLowerCase().includes(ms.toLowerCase()))return false;return true});

return(<div className="flex flex-col h-full bg-background"><Toaster richColors theme="dark" position="top-center"/>
<div className="shrink-0 border-b border-border bg-card/50 px-3 py-2"><div className="max-w-3xl mx-auto relative" ref={dr}>
<button type="button" onClick={()=>{setShowM(!showM);setMs("");setMt("all")}} className="w-full flex items-center justify-between gap-2 px-3 py-2.5 rounded-xl border border-border hover:border-primary/30 bg-secondary/30 hover:bg-secondary/50 transition-all text-left">
<div className="flex items-center gap-2.5 min-w-0"><div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0"><Brain className="w-4 h-4 text-primary"/></div><div className="min-w-0"><div className="text-sm font-semibold truncate">{cm.name}</div><div className="text-[11px] text-muted-foreground flex items-center gap-1.5 mt-0.5">{cm.p}{cm.f?<span className="ml-1 text-green-400 font-medium">Gratuit</span>:<span className="ml-1 text-amber-400 font-medium">${cm.r}/1M</span>}</div></div></div>
<div className="flex items-center gap-2 shrink-0"><span className="text-[10px] text-muted-foreground bg-secondary px-2 py-0.5 rounded-full">{frees.length} gratuits &middot; {paids.length} payants</span><ChevronDown className={`w-4 h-4 text-muted-foreground transition-transform ${showM?"rotate-180":""}`}/></div></button>
{showM&&<div className="absolute top-full mt-2 left-0 right-0 bg-card border border-border rounded-xl shadow-2xl overflow-hidden z-50"><div className="p-2 border-b border-border"><div className="relative"><Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground"/><input value={ms} onChange={e=>setMs(e.target.value)} placeholder="Rechercher..." className="w-full bg-secondary/50 rounded-lg pl-8 pr-3 py-2 text-xs outline-none" autoFocus/></div>
<div className="flex gap-1 mt-2"><button type="button" onClick={()=>setMt("all")} className={`text-[11px] px-2.5 py-1 rounded-md ${mt==="all"?"bg-primary/20 text-primary font-medium":"text-muted-foreground"}`}>Tous</button><button type="button" onClick={()=>setMt("free")} className={`text-[11px] px-2.5 py-1 rounded-md ${mt==="free"?"bg-green-500/20 text-green-400 font-medium":"text-muted-foreground"}`}>Gratuits ({frees.length})</button><button type="button" onClick={()=>setMt("paid")} className={`text-[11px] px-2.5 py-1 rounded-md ${mt==="paid"?"bg-amber-500/20 text-amber-400 font-medium":"text-muted-foreground"}`}>Payants ({paids.length})</button></div></div>
<div className="max-h-60 overflow-y-auto">{fm.slice(0,50).map((m:any)=>(<button key={m.id} type="button" onClick={()=>sel(m.id)} className={`w-full text-left px-3 py-2 hover:bg-secondary/50 transition-colors flex items-center justify-between gap-2 border-b border-border/20 ${m.id===model?"bg-primary/5 border-l-2 border-l-primary":""}`}><div className="min-w-0"><div className="text-xs font-medium truncate">{m.name}</div><div className="text-[10px] text-muted-foreground truncate">{m.p} &middot; {m.f?"Gratuit":"$"+m.r+"/1M"}</div></div><div className="shrink-0 flex items-center gap-1.5">{m.f?<span className="text-[10px] bg-green-500/15 text-green-400 px-1.5 py-0.5 rounded font-medium">Gratuit</span>:<span className="text-[10px] bg-amber-500/15 text-amber-400 px-1.5 py-0.5 rounded font-medium">${m.r}/1M</span>}{m.v&&<Image className="h-3 w-3 text-blue-400"/>}{m.id===model&&<div className="w-2 h-2 rounded-full bg-primary"/>}</div></button>))}</div></div>}
</div></div>

<div ref={sr} className="flex-1 overflow-y-auto">{msgs.length===0?(<div className="flex flex-col items-center justify-center h-full px-6 text-center py-8"><div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center mb-5"><Brain className="w-7 h-7 text-primary/40"/></div><h1 className="text-xl font-bold mb-2">ElshalflowAI</h1><p className="text-muted-foreground text-xs max-w-xs mb-6">Choisis un modele ci-dessus et commence.</p><div className="w-full max-w-xs space-y-2"><p className="text-[10px] text-muted-foreground uppercase text-left">Gratuits</p><div className="grid grid-cols-2 gap-1.5">{frees.slice(0,6).map((m:any)=>(<button key={m.id} type="button" onClick={()=>sel(m.id)} className="text-left p-2 rounded-lg border border-border hover:border-primary/30 bg-secondary/30"><div className="text-[11px] font-medium truncate">{m.name}</div><div className="text-[9px] text-green-400 mt-0.5">{m.p}</div></button>))}</div></div></div>):(<div className="max-w-3xl mx-auto px-3 py-5 space-y-5">{msgs.map((msg:any)=>(<div key={msg.id} className={`flex ${msg.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[85%] ${msg.role==="user"?"flex flex-col items-end":""}`}>{msg.images&&msg.images.length>0&&<div className="flex gap-1 mb-1 flex-wrap justify-end">{msg.images.map((img:string,i:number)=><img key={i} src={img} alt="" className="max-w-[120px] max-h-[120px] rounded-lg object-cover"/>)}</div>}<div className={`px-3 py-2.5 text-[13px] leading-relaxed rounded-2xl ${msg.role==="user"?"bg-primary/15 text-foreground rounded-br-md":""}`}>{msg.content?render(msg.content):<span className="flex gap-1"><span className="w-1.5 h-1.5 rounded-full bg-muted-foreground animate-bounce"/><span className="w-1.5 h-1.5 rounded-full bg-muted-foreground animate-bounce" style={{animationDelay:"0.15s"}}/><span className="w-1.5 h-1.5 rounded-full bg-muted-foreground animate-bounce" style={{animationDelay:"0.3s"}}/></span>}</div></div></div>))}{loading&&msgs[msgs.length-1]?.role==="user"&&<div className="flex justify-start"><div className="px-3 py-2.5"><span className="flex gap-1"><span className="w-1.5 h-1.5 rounded-full bg-primary/60 animate-bounce"/><span className="w-1.5 h-1.5 rounded-full bg-primary/60 animate-bounce" style={{animationDelay:"0.15s"}}/><span className="w-1.5 h-1.5 rounded-full bg-primary/60 animate-bounce" style={{animationDelay:"0.3s"}}/></span></div></div>}</div>)}</div>
{images.length>0&&<div className="px-3 pb-1 flex gap-1.5 flex-wrap max-w-3xl mx-auto w-full">{images.map((img:any,i:number)=>(<div key={i} className="relative group"><img src={img.preview} alt="" className="h-12 w-12 rounded-lg object-cover border border-border"/><button type="button" onClick={()=>rmImg(i)} className="absolute -top-1.5 -right-1.5 bg-red-500 rounded-full p-0.5 opacity-0 group-hover:opacity-100"><X className="h-2.5 w-2.5 text-white"/></button></div>))}</div>}
<div className="border-t border-border px-2 py-2.5"><div className="max-w-3xl mx-auto"><form onSubmit={handleSubmit} className="flex items-end gap-1.5 bg-secondary/40 rounded-2xl border border-border focus-within:border-primary/30 transition-colors px-2.5 py-1.5"><button type="button" onClick={()=>fr.current?.click()} className="p-1 text-muted-foreground hover:text-foreground shrink-0"><Paperclip className="h-3.5 w-3.5"/></button><input ref={fr} type="file" accept="image/*" multiple className="hidden" onChange={e=>e.target.files&&hFiles(e.target.files)}/><textarea value={input} onChange={e=>setInput(e.target.value)} onPaste={hPaste} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();handleSubmit(e)}}} placeholder="Message ElshalflowAI..." rows={1} className="flex-1 bg-transparent resize-none text-[13px] outline-none placeholder:text-muted-foreground min-h-[22px] max-h-[120px] py-0.5" disabled={loading}/><div className="flex items-center gap-1 shrink-0">{loading?<button type="button" onClick={()=>ar.current?.abort()} className="p-1 text-red-400"><StopCircle className="h-3.5 w-3.5"/></button>:<button type="submit" disabled={!input.trim()&&images.length===0} className="p-1 text-primary hover:text-primary/80 disabled:text-muted-foreground disabled:opacity-40"><Send className="h-3.5 w-3.5"/></button>}</div></form><p className="text-[9px] text-muted-foreground text-center mt-1">{!getKey()?"Ajoutez cle OpenRouter dans Cles API &middot; ":""}Entree = envoyer</p></div></div></div>);
}
